microedition: io: Stub some functions of Connector.java
Certain versions of Arcadius (which is now fixed since Tiled Layer
works) call for Connector.open(String), and since those were
commented out in FreeJ2ME, the result was a java.lang.NoSuchMethodError

Now it just plays normally (free version gets stuck on the menu
since "network" isn't implemented yet)