RecordStore: I keep forgetting java.nio does not exist in Java 6.
So yeah, despite Java 8's compiler not complaining about their
presence with the target being set to Java 6, actually using them
would hit a NoClassDefFoundError.